apiVersion: v1
kind: Pod
metadata:
  name: empty-pod
spec:
  containers:
    - name: webserver
      image: nginx:1.14
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html


  volumes:
    - name: html
      emptyDir: {}
