apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-deployment
  namespace: chan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: peksoon/mysql:1.0.0
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: chan
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306


