apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  namespace: chan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: tomcat-pod
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat-container
          image: peksoon/tomcat:1.0.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: chan
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - port: 8080
      nodePort: 30001
