apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-mainui
spec:
  replicas: 2
  selector:
    matchLables:
      name: apache
      app: main
    matchExpressions:
      - key: rel
        operator: In
        values: 
         - "2.1"
         - "2.2"
  template:
    metadata:
      name: apache-pod
      labels:
        name: apache
        app: main
        rel: "2.2"
    spec:
      containers:
        - name: apache-container
          image: httpd:2.2
          ports:
            - containerPort: 80