apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    builder: "JCH(jch951753@gmail.com)"
    buildDate: "2023-04-13"
    imageRegistry: https://hub.docker.com
spec:
  containers:
    - name: nginx
      image: nginx:1.14
      ports:
        - containerPort: 80
