apiVersion: v1
kind: Pod
metadata:
  name: pod-nodeselection
spec:
  nodeSelector:
    gpu: "true"
    disk: ssd
  containers:
    - name: nginx
      image: nginx:1.14
      ports:
        - containerPort: 80
